In [112]:
import cv2  
import numpy

## Face Detection

In [113]:
img=cv2.imread("./Downloads/images/man1.jpg")

In [114]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [115]:
face_cascade=cv2.CascadeClassifier('./Downloads/cascade_classifier/haarcascade_frontalface_default.xml')

In [116]:
faces,num_detection=face_cascade.detectMultiScale2(img)

In [117]:
faces

array([[ 76, 121, 366, 366]])

In [118]:
print(faces)


[[ 76 121 366 366]]


In [119]:
print(num_detection)

[53]


In [120]:
pt1=(faces[0][0],faces[0][1])
pt2=(faces[0][0]+faces[0][2],faces[0][1]+faces[0][3])
cv2.rectangle(img,pt1,pt2,(0,255,0))
cv2.imshow("Face Detection",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [121]:
#draw the circle 
cx=76+366 //2
cy=121+366 //2
r=366//2 
 
cv2.circle(img,(cx,cy),r,(0,255,255),2)
cv2.imshow('Face Detection Circle',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [122]:
img=cv2.imread('./Downloads/images/friends.jpg') 
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [123]:
#Mutliple face recognition 
face_cascade=cv2.CascadeClassifier('./Downloads/cascade_classifier/haarcascade_frontalface_default.xml') 
 
#Step 1:Apply Cascade Classifier to an image
faces,num_detection=face_cascade.detectMultiScale2(img,minNeighbors=8) 
print(faces) 
#Step 2:Run a loop 
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))

#Step3:Displaying the results 
cv2.imshow('face detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[251  65 103 103]
 [ 44 117 100 100]
 [450  66 102 102]]


In [124]:
print(num_detection)

[84 86 74]


## Face and Eye Detection 

In [125]:
face_cascade=cv2.CascadeClassifier('./Downloads/cascade_classifier/haarcascade_frontalface_default.xml')  
eye_cascade=cv2.CascadeClassifier('./Downloads/cascade_classifier/haarcascade_eye.xml') 

In [126]:
faces,num_detection_face=face_cascade.detectMultiScale2(img,minNeighbors=8)
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
     
    #Cropping the image    
    face_roi=img[y:y+h,x:x+h]
    #Applying cascade classifier to an face to detect eyes 
    eyes,num_detection_eyes=eye_cascade.detectMultiScale2(face_roi)
    for ex,ey,ew,eh in eyes:
        cx=x+ex+ew//2
        cy=y+ey+eh//2
        r=eh//2
        cv2.circle(img,(cx,cy),r,(255,0,255),2)
         
    
    
cv2.imshow('Face Detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
        
    

## Smile Detection 

In [127]:
face_cascade=cv2.CascadeClassifier('./Downloads/cascade_classifier/haarcascade_frontalface_default.xml')  
eye_cascade=cv2.CascadeClassifier('./Downloads/cascade_classifier/haarcascade_eye.xml')  
smile_cascade=cv2.CascadeClassifier('./Downloads/cascade_classifier/haarcascade_smile.xml')   


faces,num_detection_face=face_cascade.detectMultiScale2(img,minNeighbors=8)
for x,y,w,h in faces:
    face_roi=img[y:y+h,x:x+h].copy()
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
     
    #Applying cascade classifier to an face to detect eyes 
    eyes,num_detection_eyes=eye_cascade.detectMultiScale2(face_roi)
    for ex,ey,ew,eh in eyes:
        cx=x+ex+ew//2
        cy=y+ey+eh//2
        r=eh//2
        cv2.circle(img,(cx,cy),r,(255,0,255),2) 
        
        
    smiles,num_detection_smiles=smile_cascade.detectMultiScale2(face_roi)
    for sx,sy,sw,sh in smiles:
         cv2.rectangle(img,(x+sx,y+sy),(x+sx+sw,y+sy+sh),(255,0,0),2) 
            

cv2.imshow('face eye smile detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
        
    